@startuml
    object "cloneDeep" as clone_deep_91af3a80 {
      lodash.clonedeep.ts
    }
    object "util" as util_6f8bd708 {
      util.ts
    }
    folder "src" as src_b874d07 {
      card class_type_e4ba24f3 [
        ClassType
        ---
        new (...args: T extends { new (...args: infer P): any } ? P : never[]) => T
      ]
      object "classFactoryPattern" as class_factory_pattern_e4ba24f3 {
      }
      interface "JoiLogger" as joi_logger_68a048a4 {
        + warn(msg: string,\n     obj: ObjectType): void
      }
      card joi_util_options_68a048a4 [
        joiUtilOptions
        ---
        ValidationOptions & {
          logger?: JoiLogger
        }
      ]
      class "ErrorWithPayload" as error_with_payload_68a048a4 {
        constructor(message: string,\n     payload: T)
        payload: T
      }
      class "JoiUtil" as joi_util_68a048a4 {
        # _validate(objectToValidate: any,\n     schema: Schema | ObjectSchema<T>,\n     options?: joiUtilOptions): T
        sanitize(objectToValidate: any,\n     schema: Schema | ObjectSchema<T>,\n     joiUtilOptions?: joiUtilOptions): T
        validate(objectToValidate: any,\n     schema: Schema | ObjectSchema<T>,\n     joiUtilOptions?: joiUtilOptions): T
      }
      object "memoizeFactory" as memoize_factory_7591f384 {
      }
      card object_type_a28a167d [
        ObjectType
        ---
        { [k: string]: any }
      ]
      class "ObjectUtil" as object_util_a28a167d {
        deepClone(objectToClone: T): T
        deepEqual(a: any,\n     b: any): boolean
        deepNullToUndefined(objectWithNulls: T): T
        deepStringify(obj: any,\n     options?: {\n     isSorted?: boolean;\n     compact?: boolean | number \n}): string
        pickByList(obj: T,\n     keyList: (L | string)[]): Pick<T,\n     L>
        pickByObjectKeys(obj: T,\n     objWithPickKeys: Partial<T> | ObjectType): Pick<T,\n     L>
      }
      object "regexUtil" as regex_util_4ac1c785 {
        + uuid: const
      }
      class "SingleThresholdPromise" as single_threshold_promise_174db0f3 {
        # _cache: {\n    promises?: { resolve: (value: T | PromiseLike<T>) => void; reject: (reason?: any) => void }[]\n  }
        # _factoryFn: AnyFunctionPromiseNoParams<T>
        # _rejectPromises: void
        constructor(factoryFn: AnyFunctionPromiseNoParams<T>)
        promise: Promise<T>
      }
      object "stringUtil" as string_util_12a47d9d {
        + generateUUID: string
      }
      enum "DurationUnit" as duration_unit_c35fc59d {
        DAY = 'DAY'
        HOUR = 'HOUR'
        MILLISECOND = 'MILLISECOND'
        MINUTE = 'MINUTE'
        MONTH = 'MONTH'
        SECOND = 'SECOND'
        WEEK = 'WEEK'
        YEAR = 'YEAR'
      }
      card duration_unit_type_c35fc59d [
        DurationUnitType
        ---
        `${DurationUnit}`
      ]
      class "TimeUtil" as time_util_c35fc59d {
        addToDate(params: {\n     unit: DurationUnitType | DurationUnit;\n     value: number;\n     date: Date \n}): Date
        dateToUnix(date: Date): number
        dateToUnixSec(date: Date): number
        now: Date
        unixSecToDate(unix: number): Date
        unixToDate(unix: number): Date
      }
      object "timeout" as timeout_67d0ec7a {
      }
      object "typeUtil" as type_util_3bdc4f90 {
        + exhaustiveError(message: string,\n     _: never): Error
        + exhaustiveMessage(message: string,\n     _: never): string
      }
      folder "express" as express_4db1312 {
        object "expressErrorHandler" as express_error_handler_63417b19 {
        }
      }
      folder "singleton" as singleton_4e675d67 {
        class "SingletonAsync" as singleton_async_d88be747 {
          # _cache: {\n    singleton?: T\n    promises?: { resolve: (value: T | PromiseLike<T>) => void; reject: (reason?: any) => void }[]\n  }
          # _factory: AnyFunctionPromiseNoParams<T>
          # _rejectPromises(params: { error: Error }): void
          cached: T | undefined
          cleanCache: void
          constructor(factory: AnyFunctionPromiseNoParams<T>)
          promise: Promise<T>
        }
        object "singletonPattern" as singleton_pattern_9ffe3d49 {
        }
      }
      folder "types" as types_b9f6c763 {
        artifact "types.d.ts" as types_d_ts_c7688ce4 {
        }
        folder "any-function" as any_function_b59e1615 {
          card any_function_14fe44ed [
            AnyFunction
            ---
            (...args: any[]) => T
          ]
          card any_function_no_params_57476943 [
            AnyFunctionNoParams
            ---
            () => T
          ]
          card any_function_promise_no_params_e08eab31 [
            AnyFunctionPromiseNoParams
            ---
            () => Promise<T>
          ]
          card any_function_promise_7353b62c [
            AnyFunctionPromise
            ---
            (...args: any[]) => Promise<T>
          ]
        }
      }
    }
    folder "date-fns" as date_fns_5b922ce7 {
      object "add" as add_ad2961c0 {
        date-fns/add.ts
      }
      object "addMilliseconds" as add_milliseconds_713d12ee {
        date-fns/addMilliseconds.ts
      }
      object "parse" as parse_1c089414 {
        date-fns/parse.ts
      }
    }
  joi_util_68a048a4 -up-> joi_util_options_68a048a4
  joi_util_68a048a4 -up-> error_with_payload_68a048a4
  object_util_a28a167d -up-> clone_deep_91af3a80
  object_util_a28a167d -up-> util_6f8bd708
  single_threshold_promise_174db0f3 -up-> any_function_promise_no_params_e08eab31
  singleton_async_d88be747 -up-> any_function_promise_no_params_e08eab31
  singleton_pattern_9ffe3d49 -up-> any_function_no_params_57476943
  time_util_c35fc59d -up-> add_ad2961c0
  time_util_c35fc59d -up-> add_milliseconds_713d12ee
  time_util_c35fc59d -up-> parse_1c089414
@enduml