version: v1.0
name: Prod Deploy
agent:
  machine:
    type: e1-standard-2
    os_image: ubuntu2004

blocks:
  - name: Deploy to Production
    task:
      secrets:
        - name: mb-docker-hub
        - name: bc-git-secret
        - name: bc-npm-secret
      jobs:
        - name: Deploy
          commands:
            - echo $DOCKER_PASSWORD | docker login --username "$DOCKER_USERNAME" --password-stdin
            - cache restore bc-msh-util-version-$SEMAPHORE_GIT_SHA
            - export $(cat version.txt)
            - rm version.txt
            - checkout
            - git remote rm origin
            - git remote add origin https://$GH_USER:$GH_TOKEN@github.com/beecode-rs/msh-util.git
            - git checkout tags/v$VERSION -b tmp-prod-branch
            - docker build -f .docker/Dockerfile -t bc-msh-util-deploy .
            - docker run --rm -e CI bc-msh-util-deploy sh -c "npm config set '//registry.npmjs.org/:_authToken' $NPM_TOKEN && git tag v$VERSION-prod && git push origin --tags && npm publish --access public"
    skip:
      when: branch != 'main'
