version: v1.0
name: Prod Deploy
agent:
  machine:
    type: e1-standard-2
    os_image: ubuntu2004

blocks:
  - name: Deploy to Production
    task:
      secrets:
        - name: mb-docker-hub
        - name: bc-git-secret
        - name: bc-npm-secret
      jobs:
        - name: Deploy
          commands:
            - echo $DOCKER_PASSWORD | docker login --username "$DOCKER_USERNAME" --password-stdin
            - cache restore bc-msh-util-version-$SEMAPHORE_GIT_SHA
            - export $(cat version.txt)
            - rm version.txt
            - checkout
            - git remote rm origin
            - git remote add origin https://$GH_USER:$GH_TOKEN@github.com/beecode-rs/msh-util.git
            - git checkout tags/v$VERSION -b tmp-prod-branch
            - docker build -f .docker/Dockerfile -t bc-msh-util .
            - docker build -f .docker/Dockerfile.deploy -t bc-msh-util-deploy --build-arg VERSION=$VERSION --build-arg NPM_TOKEN=$NPM_TOKEN --build-arg DEPLOY_CHANNEL=prod --build-arg CI=$CI .
            - docker run --rm bc-msh-util-deploy npm publish --access public
    skip:
      when: branch != 'main'
